gestionalumnos/urls.py
from django.conf.urls import patterns, include, url
from principal.forms import ValidatingPasswordChangeForm
from django.contrib.auth import views as auth_views

# Custom error views
handler404 = 'principal.views.StaticViews.error_404'
handler500 = 'principal.views.StaticViews.error_500'

urlpatterns = patterns(
    '',
    # Translation URLS
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Application views
    url(r'^$', 'principal.views.StaticViews.home'),
    url(r'^cookies_policy$', 'principal.views.StaticViews.cookies_policy'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}),
    url(r'^password_change/$', auth_views.password_change, {'password_change_form': ValidatingPasswordChangeForm,'template_name': 'user/password_change.html', 'post_change_redirect': '/'}),
    url(r'^logout/$', auth_views.logout_then_login),
    url(r'^admin/certification/create', 'principal.views.CertificationViews.create_certification'),
    url(r'^admin/certification/list', 'principal.views.CertificationViews.list_certifications'),
    url(r'^admin/certification/search/$', 'principal.views.CertificationViews.search'),
    url(r'^admin/certification/delete/(?P<certification_id>[0-9]+)$', 'principal.views.CertificationViews.delete_certification'),
    url(r'^admin/certification/details/(?P<certification_id>[0-9]+)$', 'principal.views.CertificationViews.details_certification'),
    url(r'^lecturer/details/(?P<lecturer_id>[0-9]+)?$', 'principal.views.TutorialViews.view_tutorials'),
    url(r'^subject/list/', 'principal.views.SubjectViews.list_subjects'),
    url(r'^student/lecturer/list/(?P<subject_id>[0-9]+)$', 'principal.views.LecturerViews.list_lecturers'),
    url(r'^student/tutorial/create/$', 'principal.views.TutorialViews.create_tutorial'),
    url(r'^rest/lecturer/(?P<subject_id>[0-9]+)$', 'principal.views.LecturerViews.get_lecturers_json'),
    url(r'^rest/subject/all$', 'principal.views.SubjectViews.get_all_json'),
    url(r'^admin/department/list', 'principal.views.DepartmentViews.list_departments'),
    url(r'^admin/department/edit/(?P<department_id>[0-9]+)?$', 'principal.views.DepartmentViews.edit_department'),
    url(r'^admin/department/search/$', 'principal.views.DepartmentViews.search'),
    url(r'^admin/department/details/(?P<department_id>[0-9]+)$', 'principal.views.DepartmentViews.details_department'),
    url(r'^admin/user/create', 'principal.views.UserViews.create_user'),
    url(r'^admin/user/list', 'principal.views.UserViews.list_users'),
    url(r'^admin/user/delete/(?P<user_id>[0-9]+)$', 'principal.views.UserViews.delete_user'),
    url(r'^admin/user/search/$', 'principal.views.UserViews.search'),
    url(r'^admin/user/details/(?P<user_id>[0-9]+)$', 'principal.views.UserViews.details_user'),
    url(r'^profile/view/(?P<student_id>[0-9]+)?$', 'principal.views.ProfileViews.view_profile'),
    url(r'^admin/subject/create', 'principal.views.SubjectViews.create_subject'),
    url(r'^admin/subject/link/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectLinkViews.create'),
    url(r'^subject/details/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectViews.subject_details'),
    url(r'^admin/subject/delete/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectViews.delete_subject'),
    url(r'^admin/subject/delete/users/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectViews.delete_users_subject'),
    url(r'^student/profile/edit$', 'principal.views.ProfileViews.edit_profile'),
    url(r'^lecturer/tutorial/edit/(?P<tutorial_id>[0-9]+)$', 'principal.views.TutorialViews.view_tutorials'),
    url(r'^lecturer/tutorial/delete/(?P<tutorial_id>[0-9]+)$', 'principal.views.TutorialViews.delete_tutorial'),
    url(r'^lecturer/tutorial/enable', 'principal.views.TutorialViews.enable_tutorials'),
    url(r'^lecturer/tutorial/disable', 'principal.views.TutorialViews.disable_tutorials'),
    url(r'^lecturer/tutorialRequest/list', 'principal.views.TutorialRequestViews.view_requests'),
    url(r'^lecturer/request/accept/(?P<tutorial_request_id>[0-9]+)$', 'principal.views.TutorialRequestViews.accept_request'),
    url(r'^lecturer/request/reject$', 'principal.views.TutorialRequestViews.view_requests'),
    url(r'^tutorialRequest/accepted', 'principal.views.TutorialRequestViews.accepted_requests'),
    url(r'^student/tutorialRequest/all', 'principal.views.TutorialRequestViews.student_all_requests'),
    url(r'^rest/lecturer/tutorial/(?P<timestamp_from>[0-9]+)/(?P<timestamp_to>[0-9]+)/(?P<utc_offset>-?[0-9]+)$', 'principal.views.TutorialViews.tutorials_json'),
    url(r'^admin/subject/link/user/(?P<subject_id>[0-9]+)/(?P<user_id>[0-9]+)?$', 'principal.views.SubjectLinkViews.link_user_subject'),
    url(r'^admin/subject/unlink/user/(?P<subject_id>[0-9]+)/(?P<user_id>[0-9]+)$', 'principal.views.SubjectLinkViews.unlink_user_subject'),
    url(r'^admin/user/import/$', 'principal.views.UserViews.import_users'),
    url(r'^admin/department/import/$', 'principal.views.DepartmentViews.import_department'),
    url(r'^lecturer/tutorial/calendar/$', 'principal.views.TutorialRequestViews.tutorial_calendar'),
    url(r'^lecturer/student/list/$', 'principal.views.ProfileViews.lecturer_students'),
    url(r'^lecturer/profile/edit/$', 'principal.views.ProfileViews.edit_lecturer'),
    url(r'^news/((?P<new_id>[0-9]+)/(?P<method>\w{2}))?$', 'principal.views.NewViews.news'),
    url(r'^news/add$', 'principal.views.NewViews.news'),
    url(r'^new/save', 'principal.views.NewViews.news'),
    url(r'^admin/subject/import/$', 'principal.views.SubjectViews.import_subject'),
    url(r'^admin/subject/import/link/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectLinkViews.import_link_subject'),
    url(r'^admin/subject/unlink/certification/(?P<subject_id>[0-9]+)/(?P<certification_id>[0-9]+)$', 'principal.views.SubjectLinkViews.unlink_certification_subject'),
    url(r'^student/tutorial/seek/(?P<lecturer_id>[0-9]+)?', 'principal.views.TutorialRequestViews.seek_tutorial'),
    url(r'^rest/tutorials', 'principal.views.TutorialRequestViews.tutorials_json'),
    url(r'^subject/search/$', 'principal.views.SubjectViews.search'),
    url(r'^lecturer/tutorial/assign', 'principal.views.TutorialRequestViews.auto_assign_tutorial'),
    url(r'^rest/lecturer/request/accept', 'principal.views.TutorialRequestViews.accept_from_mail'),
)

principal/models.py
# -*- coding: utf-8 -*-
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    AbstractBaseUser
)
from django.utils.translation import ugettext_lazy as _
import datetime
import uuid


class Alumno(User):
    # -------------- Relationships -------------------
    ficha = models.OneToOneField('Ficha', db_column='idFicha', null=True)
    asignaturas = models.ManyToManyField('Asignatura')
    dni = models.CharField(max_length=9, unique=True)

    class Meta:
        ordering = ['last_name']
        db_table = 'alumno'
        permissions = (
            ('alumno', 'Alumno'),
        )

    def __unicode__(self):
        return self.last_name + ', ' + self.first_name


class Asignatura(models.Model):
    TIPO_ASIGNATURA_CHOICES = (
        ('FB', _('Basic formation')),
        ('OB', _('Compulsory')),
        ('OP', _('Optional')),
        ('TFG', _('Final degree thesis')),

    )

    DURACION_CHOICES = (
        ('A', _('Annual')),
        ('C', _('Quarterly')),
    )
    id = models.AutoField(db_column='idAsignatura', primary_key=True)
    cuatrimestre = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(2)])
    nombre = models.CharField(max_length=100)
    curso = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    codigo = models.CharField(max_length=255, unique=True)
    creditos = models.FloatField()
    duracion = models.CharField(max_length=1, choices=DURACION_CHOICES)
    web = models.CharField(max_length=150)
    tipo_asignatura = models.CharField(db_column='tipoAsignatura', max_length=3, choices=TIPO_ASIGNATURA_CHOICES)

    # -------------- Relationships -------------------
    departamento = models.ForeignKey('Departamento', db_column='departamento')

    class Meta:
        db_table = 'asignatura'
        permissions = (('view_subject_details', 'Can view subject details'),)

    def __unicode__(self):
        return self.nombre


class Departamento(models.Model):
    id = models.AutoField(db_column='idDepartamento', primary_key=True)
    codigo = models.CharField(max_length=255, unique=True)
    nombre = models.CharField(max_length=255)
    web = models.CharField(max_length=255)

    class Meta:
        db_table = 'departamento'

    def __unicode__(self):
        return self.nombre


class Direccion(models.Model):
    id = models.AutoField(db_column='idDireccion', primary_key=True)
    direccion = models.CharField(max_length=100)
    localizacion = models.CharField(max_length=100)
    pais = models.CharField(max_length=50)
    provincia = models.CharField(max_length=50)
    codigo_postal = models.IntegerField(db_column='codigoPostal')

    class Meta:
        db_table = 'direccion'


class Ficha(models.Model):
    id = models.AutoField(db_column='IdFicha', primary_key=True)
    fecha_actualizacion = models.DateField(db_column='fechaActualizacion', auto_now=True)
    telefono = models.CharField(max_length=9)
    movil = models.CharField(max_length=9)
    foto = models.ImageField(upload_to='static/student/', null=True, default='static/student/default.jpg')
    fecha_nacimiento = models.DateField(db_column='fechaNacimiento')

    # -------------- Relationships -------------------
    direccion_residencia = models.ForeignKey(Direccion, db_column='idDirecciona', related_name='direccion_residencia')
    direccion_estudios = models.ForeignKey(Direccion, db_column='idDireccionb', related_name='direccion_estudios')

    class Meta:
        db_table = 'ficha'

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = Ficha.objects.get(id=self.id)
            if this.foto != self.foto and this.foto.name != 'static/student/default.jpg':
                this.foto.delete(save=False)
        except:
            pass  # when new photo then we do nothing, normal case

        super(Ficha, self).save(*args, **kwargs)


class Imparteasignatura(models.Model):
    cargo = models.CharField(max_length=255)

    # -------------- Relationships -------------------
    profesor = models.ForeignKey('Profesor', db_column='profesor')
    asignatura = models.ForeignKey(Asignatura, db_column='asignatura')

    class Meta:
        db_table = 'imparteasignatura'
        unique_together = (('profesor', 'asignatura'),)
        permissions = (
            ('view_certification_list', 'Can view certifications list'),
        )

    def __unicode__(self):
        return '%s  (%s)' % (self.profesor, self.cargo)


class Noticia(models.Model):
    id = models.AutoField(db_column='idNoticia', primary_key=True)
    titulo = models.CharField(max_length=100, null=False, blank=False)
    texto = models.TextField(max_length=255, null=False, blank=False)
    fecha_inicio = models.DateField(db_column='fechaIni', auto_now_add=True, null=False)
    fecha_modificacion = models.DateField(db_column='fechaMod', auto_now=True, null=False)

    # -------------- Relationships -------------------
    asignatura = models.ForeignKey(Asignatura, db_column='asignatura')
    profesor = models.ForeignKey('Profesor', db_column='profesor')

    class Meta:
        db_table = 'noticia'
        ordering = ['-fecha_inicio', '-id']


class Observacion(models.Model):
    id = models.AutoField(db_column='idObservacion', primary_key=True)
    descripcion = models.CharField(max_length=255)
    fecha = models.DateField(auto_now_add=True)

    # -------------- Relationships -------------------
    profesor = models.ForeignKey('Profesor', db_column='profesor')
    alumno = models.ForeignKey(Alumno, db_column='alumno')
    asignatura = models.ForeignKey(Asignatura, db_column='asignatura')

    class Meta:
        db_table = 'observacion'


class Peticioncita(models.Model):
    ESTADO_PETICION = (
        ('EC', _('Pending')),
        ('DE', _('Rejected')),
        ('CA', _('Cancelled')),
        ('AC', _('Accepted')),
    )
    idcita = models.AutoField(db_column='idCita', primary_key=True)
    motivo = models.CharField(max_length=255)
    estado = models.CharField(max_length=15, choices=ESTADO_PETICION)
    fechacita = models.DateTimeField(db_column='fechaCita')
    fechacitafin = models.DateTimeField(db_column='fechaCitaFin')
    motivocancelacion = models.CharField(db_column='motivoCancelacion', max_length=255, null=True)
    activation_hash = models.UUIDField(default=uuid.uuid4, editable=False, null=False, blank=False, unique=True)

    # -------------- Relationships -------------------
    alumno = models.ForeignKey(Alumno, db_column='alumno')
    profesor = models.ForeignKey('Profesor', db_column='profesor')

    class Meta:
        db_table = 'peticioncita'
        permissions = (
            ('view_tutorial_request_list', 'Can view tutorial request list'),
        )

    def __unicode__(self):
        return '%s - %s %s' % (
            datetime.datetime.strftime(self.fechacita, '%H:%M'), datetime.datetime.strftime(self.fechacitafin, '%H:%M'),
            self.alumno)


class Profesor(User):
    categoria = models.CharField(max_length=100, null=True)
    telefono = models.IntegerField(null=True)
    despacho = models.CharField(max_length=100, null=True)
    web = models.URLField(max_length=100, null=True)
    motivotutorias = models.CharField(db_column='motivoTutorias', max_length=100, null=True)
    tutoriaactivada = models.BooleanField(db_column='tutoriaActivada', default=True)
    dni = models.CharField(max_length=9, unique=True)
    # intervalo = models.IntegerField(null=False, default=30)
    # -------------- Relationships -------------------
    # usuario = models.ForeignKey('Usuario', db_column='idUsuario', primary_key=True)

    class Meta:
        permissions = (
            ("profesor", "Profesor"),
        )
        db_table = 'profesor'

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    def tutoria_days(self):
        tutorials = [tutorial.dia for tutorial in self.tutoria_set.all()]
        return list(set(tutorials))


class Titulacion(models.Model):
    id = models.AutoField(db_column='idTitulacion', primary_key=True)
    codigo = models.CharField(max_length=255, unique=True)
    nombre = models.CharField(max_length=255)
    asignaturas = models.ManyToManyField(Asignatura)

    class Meta:
        db_table = 'titulacion'

    def __unicode__(self):
        return self.nombre


class Tutoria(models.Model):
    DIAS_SEMANA = (
        (1, _('Monday')),
        (2, _('Tuesday')),
        (3, _('Wednesday')),
        (4, _('Thursday')),
        (5, _('Friday')),
    )
    id = models.AutoField(db_column='idTutoria', primary_key=True)
    horainicio = models.TimeField(db_column='horaInicio')
    horafin = models.TimeField(db_column='horaFin')
    dia = models.PositiveIntegerField(choices=DIAS_SEMANA, validators=[MinValueValidator(1), MaxValueValidator(5)])

    # -------------- Relationships -------------------
    profesor = models.ForeignKey(Profesor, db_column='idUsuario')

    class Meta:
        db_table = 'tutoria'
        ordering = ['horainicio']


class Administrador(User):
    class Meta:
        permissions = (
            ('administrator', 'Administrator'),
        )
        db_table = 'administrador'

principal/views/EmailViews.py
# -*- coding: utf-8 -*-
from django.template.loader import render_to_string
from django.core.mail.message import EmailMessage
import hashlib


def send_email_create_user(user, password):
    mail_sting = render_to_string('email/register.html', {'user': user, 'password': password, 'request': request})
    send_mail([user.email], 'Bienvenido / Welcome', mail_sting)


def send_tutorial_request_mail(request, tutorial_request):
    accept_from_mail_token = hashlib.sha512(str(tutorial_request.activation_hash)).hexdigest()
    mail_sting = render_to_string('email/lecturer_tutorial_request.html',
                                  {'tutorial_request': tutorial_request, 'token': accept_from_mail_token,
                                   'request': request})
    send_mail([tutorial_request.profesor.email], 'Petición recibida / Request received', mail_sting)


def send_tutorial_accepted_mail(tutorial_request):
    mail_sting = render_to_string('email/student_request_accepted.html', {'tutorial_request': tutorial_request})
    send_mail([tutorial_request.profesor.email], 'Petición aceptada / Accepted request', mail_sting)


def send_tutorial_rejected_mail(tutorial_request):
    mail_sting = render_to_string('email/student_request_rejected.html', {'tutorial_request': tutorial_request})
    send_mail([tutorial_request.profesor.email], 'Petición rechazada / Request rejected', mail_sting)


def send_mail(to_list, subject, content):
    email = EmailMessage(subject, content, to=[to for to in to_list])
    email.content_subtype = 'html'
    email.send(fail_silently=True)

principal/templates/tutorial_request/list.html
{% extends 'layout/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load endless %}
{% load extra-tags %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">

            <h4>{{ title }}</h4>
            {% if reject_form and tutorial_requests %}
                <button type="button" class="btn btn-warning mb20" data-toggle="modal" data-target="#rejectMultipleModal">{% trans "Cancel tutorial requests" %}</button>
            {% endif %}

            <div class="row">
                {% paginate tutorial_requests %}
                {% for request in tutorial_requests %}
                    <div class="col-md-6 request-card">
                        <div class="card">
                            <div class="card-content">
                                <div class="pull-right text-center">
                                    <h4><span class="legendToggle status-label {% request_label request %}">{% trans request.get_estado_display %}</span></h4>
                                    {% if request.estado == 'DE' %}
                                        <a data-placement="bottom" href="#" data-toggle="popover" data-trigger="focus" title="{% trans "Rejection reason" %}" data-content="{{ request.motivocancelacion }}">{% trans "Why?" %}</a>
                                    {% endif %}
                                </div>
                                <p>
                                    <a href="{% if perms.principal.profesor %}/profile/view/{{ request.alumno.id }}{% else %}/lecturer/details/{{ request.profesor.id }}{% endif %}"
                                       data-toggle="tooltip" data-placement="right"
                                       title="
                                               {% if perms.principal.profesor %}{% trans "Click to view the profile of the applicant" %}{% else %}{% trans "Click to view the profile of the lecturer" %}{% endif %}">
                                        <i class="fa fa-user"></i>
                                        {% if perms.principal.profesor %}{{ request.alumno }} {% else %}
                                            {{ request.profesor }} {% endif %}
                                    </a>
                                </p>

                                <p><i class="fa fa-clock-o"></i> {{ request.fechacita }}</p>

                                <p class="text-justify text-flow"><i class="fa fa-quote-left"></i>
                                    {{ request.motivo }}
                                </p>
                            </div>
                            <div class="card-action">
                                {% if form %}
                                    <div class="btn-group btn-group-sm" role="group">
                                        <a type="button" class="btn btn-success"
                                           href="/lecturer/request/accept/{{ request.idcita }}"
                                           onclick="return confirm('{% trans "By accepting this request, all requests with the same schedule will be automatically canceled. Are you sure?" %}');">{% trans "Accept" %}</a>
                                        <a id="{{ request.idcita }}" type="button" class="btn btn-danger"
                                           data-toggle="modal" data-target="#rejectModal"
                                           onclick="rejectRequest(this);">{% trans "Reject" %}</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:2 %}
                        <div class="clearfix"></div>
                    {% endif %}
                {% empty %}
                    </div><p>
                    {% if form %}
                        {% trans "No pending requests found." %}
                    {% else %}
                        {% trans "No accepted requests found." %}
                    {% endif %}
                    </p>
                {% endfor %}
        </div>
         <div class="text-center">
                    <nav class="diggy-pagination">
                        {% show_pages %}
                    </nav>
                </div>
    </div>

    <div class="modal fade" id="legendModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <i class="fa fa-times"></i>
                    </button>
                    <h4 class="modal-title">{% trans "Legend" %}</h4>
                </div>
                <div class="modal-body">
                    <h5>{% trans "This is the meaning of the labels that appear next to requests." %}</h5>
                    <dl>
                        <dt><h4><span class="label label-primary">{% trans "Pending" %}</span></h4></dt>
                        <dd>{% trans "It means that the request is pending that the lecturer responds." %}</dd>

                        <dt><h4><span class="label label-success">{% trans "Accepted" %}</span></h4></dt>
                        <dd>{% trans "It means that the request has been accepted by the teacher." %}</dd>

                        <dt><h4><span class="label label-danger">{% trans "Cancelled" %}</span></h4></dt>
                        <dd>{% trans "This means that the request has been canceled by the system due to incompatibility of schedule." %}</dd>

                        <dt><h4><span class="label label-danger">{% trans "Rejected" %}</span></h4></dt>
                        <dd>{% trans "This means that the request has been expressly rejected by the lecturer." %}</dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">{% trans "Understood" %}</button>
                </div>
            </div>
        </div>
    </div>

    {% if form %}

        <div class="modal fade" id="rejectModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i
                                class="fa fa-times"></i></button>
                        <h4 class="modal-title">{% trans "Reject tutorial request" %}</h4>
                    </div>
                    <div class="modal-body">
                        {% display_errors form %}
                        <form action="/lecturer/request/reject" method="POST">
                            {% csrf_token %}
                            {% for field in form.hidden_fields %}
                                {{ field }}
                            {% endfor %}
                            <label for="{{ form.visible_fields.0.id_for_label }}">{{ form.visible_fields.0.label }}</label>
                            {{ form.visible_fields.0 }}
                            <input type="submit" value="Submit" id="tutorialDisableSubmit" class="hidden"/>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                        <button type="button" id="submitTrigger" class="btn btn-primary">{% trans "Submit" %}</button>
                    </div>
                </div>
            </div>
        </div>

        {% if form.errors %}
            <script type="text/javascript">
                $('#rejectModal').modal();
            </script>
        {% endif %}

        <script type="text/javascript">
            $('#submitTrigger').click(function () {
                $('#tutorialDisableSubmit').click();
            });

            function rejectRequest(element) {
                var actual_id = $('#id_request_id').val();
                var new_id = element.id;
                if (new_id != actual_id || typeof actual_id == "undefined") {
                    $('#id_request_id').val(new_id);
                    $('#id_motivation').val('');
                    $('#form-errors').remove();
                }

            }
        </script>
    {% endif %}

    {% if reject_form %}
        <div class="modal fade" id="rejectMultipleModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i
                                class="fa fa-times"></i></button>
                        <h4 class="modal-title">{% trans "Reject tutorial requests" %}</h4>
                    </div>
                    <div class="modal-body">
                        {% trans "Use control/command key to select multiple objects at once." %}
                        {% display_errors reject_form %}
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ reject_form.tutorial_requests.id_for_label }}">{{ reject_form.tutorial_requests.label }}</label>
                                {{ reject_form.tutorial_requests }}
                            </div>
                            <div class="form-group">
                                <label for="{{ reject_form.motivation.id_for_label }}">{{ reject_form.motivation.label }}</label>
                                {{ reject_form.motivation }}
                            </div>

                            <input type="submit" value="Submit" id="tutorialRejectSubmit" class="hidden"/>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                        <button type="button" id="rejectSubmitTrigger"
                                class="btn btn-primary">{% trans "Submit" %}</button>
                    </div>
                </div>
            </div>
        </div>

        {% if reject_form.errors %}
            <script type="text/javascript">
                $('#rejectMultipleModal').modal();
            </script>
        {% endif %}

        <script type="text/javascript">
            $('#rejectSubmitTrigger').click(function () {
                $('#tutorialRejectSubmit').click();
            });
        </script>
    {% endif %}

    <script type="text/javascript">
        $('.legendToggle').click(function () {
            $('#legendModal').modal();
        });
    </script>
{% endblock %}