gestionalumnos/urls.py
from django.conf.urls import patterns, include, url
from principal.forms import ValidatingPasswordChangeForm
from django.contrib.auth import views as auth_views

# Custom error views
handler404 = 'principal.views.StaticViews.error_404'
handler500 = 'principal.views.StaticViews.error_500'

urlpatterns = patterns(
    '',
    # Translation URLS
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Application views
    url(r'^$', 'principal.views.StaticViews.home'),
    url(r'^cookies_policy$', 'principal.views.StaticViews.cookies_policy'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}),
    url(r'^password_change/$', auth_views.password_change, {'password_change_form': ValidatingPasswordChangeForm,'template_name': 'user/password_change.html', 'post_change_redirect': '/'}),
    url(r'^logout/$', auth_views.logout_then_login),
    url(r'^admin/certification/create', 'principal.views.CertificationViews.create_certification'),
    url(r'^admin/certification/list', 'principal.views.CertificationViews.list_certifications'),
    url(r'^admin/certification/search/$', 'principal.views.CertificationViews.search'),
    url(r'^admin/certification/delete/(?P<certification_id>[0-9]+)$', 'principal.views.CertificationViews.delete_certification'),
    url(r'^admin/certification/details/(?P<certification_id>[0-9]+)$', 'principal.views.CertificationViews.details_certification'),
    url(r'^lecturer/details/(?P<lecturer_id>[0-9]+)?$', 'principal.views.TutorialViews.view_tutorials'),
    url(r'^subject/list/', 'principal.views.SubjectViews.list_subjects'),
    url(r'^student/lecturer/list/(?P<subject_id>[0-9]+)$', 'principal.views.LecturerViews.list_lecturers'),
    url(r'^student/tutorial/create/$', 'principal.views.TutorialViews.create_tutorial'),
    url(r'^rest/lecturer/(?P<subject_id>[0-9]+)$', 'principal.views.LecturerViews.get_lecturers_json'),
    url(r'^rest/subject/all$', 'principal.views.SubjectViews.get_all_json'),
    url(r'^admin/department/list', 'principal.views.DepartmentViews.list_departments'),
    url(r'^admin/department/edit/(?P<department_id>[0-9]+)?$', 'principal.views.DepartmentViews.edit_department'),
    url(r'^admin/department/search/$', 'principal.views.DepartmentViews.search'),
    url(r'^admin/department/details/(?P<department_id>[0-9]+)$', 'principal.views.DepartmentViews.details_department'),
    url(r'^admin/user/create', 'principal.views.UserViews.create_user'),
    url(r'^admin/user/list', 'principal.views.UserViews.list_users'),
    url(r'^admin/user/delete/(?P<user_id>[0-9]+)$', 'principal.views.UserViews.delete_user'),
    url(r'^admin/user/search/$', 'principal.views.UserViews.search'),
    url(r'^admin/user/details/(?P<user_id>[0-9]+)$', 'principal.views.UserViews.details_user'),
    url(r'^profile/view/(?P<student_id>[0-9]+)?$', 'principal.views.ProfileViews.view_profile'),
    url(r'^admin/subject/create', 'principal.views.SubjectViews.create_subject'),
    url(r'^admin/subject/link/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectLinkViews.create'),
    url(r'^subject/details/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectViews.subject_details'),
    url(r'^admin/subject/delete/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectViews.delete_subject'),
    url(r'^admin/subject/delete/users/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectViews.delete_users_subject'),
    url(r'^student/profile/edit$', 'principal.views.ProfileViews.edit_profile'),
    url(r'^lecturer/tutorial/edit/(?P<tutorial_id>[0-9]+)$', 'principal.views.TutorialViews.view_tutorials'),
    url(r'^lecturer/tutorial/delete/(?P<tutorial_id>[0-9]+)$', 'principal.views.TutorialViews.delete_tutorial'),
    url(r'^lecturer/tutorial/enable', 'principal.views.TutorialViews.enable_tutorials'),
    url(r'^lecturer/tutorial/disable', 'principal.views.TutorialViews.disable_tutorials'),
    url(r'^lecturer/tutorialRequest/list', 'principal.views.TutorialRequestViews.view_requests'),
    url(r'^lecturer/request/accept/(?P<tutorial_request_id>[0-9]+)$', 'principal.views.TutorialRequestViews.accept_request'),
    url(r'^lecturer/request/reject$', 'principal.views.TutorialRequestViews.view_requests'),
    url(r'^tutorialRequest/accepted', 'principal.views.TutorialRequestViews.accepted_requests'),
    url(r'^student/tutorialRequest/all', 'principal.views.TutorialRequestViews.student_all_requests'),
    url(r'^rest/lecturer/tutorial/(?P<timestamp_from>[0-9]+)/(?P<timestamp_to>[0-9]+)/(?P<utc_offset>-?[0-9]+)$', 'principal.views.TutorialViews.tutorials_json'),
    url(r'^admin/subject/link/user/(?P<subject_id>[0-9]+)/(?P<user_id>[0-9]+)?$', 'principal.views.SubjectLinkViews.link_user_subject'),
    url(r'^admin/subject/unlink/user/(?P<subject_id>[0-9]+)/(?P<user_id>[0-9]+)$', 'principal.views.SubjectLinkViews.unlink_user_subject'),
    url(r'^admin/user/import/$', 'principal.views.UserViews.import_users'),
    url(r'^admin/department/import/$', 'principal.views.DepartmentViews.import_department'),
    url(r'^lecturer/tutorial/calendar/$', 'principal.views.TutorialRequestViews.tutorial_calendar'),
    url(r'^lecturer/student/list/$', 'principal.views.ProfileViews.lecturer_students'),
    url(r'^lecturer/profile/edit/$', 'principal.views.ProfileViews.edit_lecturer'),
    url(r'^news/((?P<new_id>[0-9]+)/(?P<method>\w{2}))?$', 'principal.views.NewViews.news'),
    url(r'^news/add$', 'principal.views.NewViews.news'),
    url(r'^new/save', 'principal.views.NewViews.news'),
    url(r'^admin/subject/import/$', 'principal.views.SubjectViews.import_subject'),
    url(r'^admin/subject/import/link/(?P<subject_id>[0-9]+)$', 'principal.views.SubjectLinkViews.import_link_subject'),
    url(r'^admin/subject/unlink/certification/(?P<subject_id>[0-9]+)/(?P<certification_id>[0-9]+)$', 'principal.views.SubjectLinkViews.unlink_certification_subject'),
    url(r'^student/tutorial/seek/(?P<lecturer_id>[0-9]+)?', 'principal.views.TutorialRequestViews.seek_tutorial'),
    url(r'^rest/tutorials', 'principal.views.TutorialRequestViews.tutorials_json'),
    url(r'^subject/search/$', 'principal.views.SubjectViews.search'),
    url(r'^lecturer/tutorial/assign', 'principal.views.TutorialRequestViews.auto_assign_tutorial'),
    url(r'^rest/lecturer/request/accept', 'principal.views.TutorialRequestViews.accept_from_mail'),
)

principal/forms.py
# -*- coding: utf-8 -*-

from django import forms
from principal.validators import username_validator
from principal.services import CertificationService, DepartmentService, UserService, SubjectService
from principal.models import Departamento, Titulacion, Alumno
import datetime
from django.contrib.auth.models import User
from principal.models import Profesor, Tutoria, Peticioncita, Imparteasignatura
from principal.services import PeticionCitaService, StudentService, LecturerService

from django.utils.translation import ugettext as _
from django.contrib.auth.forms import PasswordChangeForm
import re


class PeticionCitaForm(forms.Form):
    subject = forms.IntegerField(label=_('Subject'),
                                 widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'}),
                                 required=True)
    lecturer_id = forms.IntegerField(label=_('Lecturer'),
                                     widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'}),
                                     required=True)


class CertificationEditForm(forms.Form):
    code = forms.DecimalField(
        label='code',
        required=True,
        max_digits=254,
        min_value=0,
        decimal_places=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'min': '0',
                'data-maxlength': '254',
            }
        )
    )

    name = forms.CharField(
        label='name',
        required=True,
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '254',
            }
        )
    )

    def clean(self):
        code = self.cleaned_data.get('code')
        if code is not None:
            certification = CertificationService.find_by_code(code)
            if certification is not None:
                self.add_error('code', _("There cannot be two certifications with the same code"))

        return self.cleaned_data


class DepartmentEditForm(forms.Form):
    id = forms.IntegerField(
        required=False,
        widget=forms.HiddenInput
    )

    code = forms.DecimalField(
        label='code',
        required=True,
        max_digits=254,
        min_value=0,
        decimal_places=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'min': '0',
                'data-maxlength': '254',
            }
        )
    )

    name = forms.CharField(
        label='name',
        required=True,
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '254',
            }
        )
    )

    web = forms.URLField(
        label='web',
        required=True,
        max_length=254,
        widget=forms.URLInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '254',
            }
        )
    )

    def clean(self):

        id_departament = self.cleaned_data.get('id')
        code = self.cleaned_data.get('code')

        if code:
            departament = DepartmentService.find_by_code(code)
            # Al editar puede existir otro departamento con el mismo codigo
            if id_departament:
                if departament.id != id_departament:
                    self.add_error('code', _("There cannot be two certifications with the same code"))
            else:
                if departament:
                    self.add_error('code', _("There cannot be two certifications with the same code"))

        return self.cleaned_data


class UserEditForm(forms.Form):
    RADIO_CHOICES = (
        ('st', _("Student")),
        ('le', _("Lecturer")),
    )

    first_name = forms.CharField(
        required=True,
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '254',
            }
        )
    )

    last_name = forms.CharField(
        required=True,
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '30',
            }
        )
    )

    user = forms.CharField(
        required=True,
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '254',
            }
        )
    )

    dni = forms.CharField(
        required=True,
        max_length=9,
        validators=[username_validator],
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '9',
                'pattern': '^\d{8}[A-Z]$'
            }
        )
    )

    type = forms.ChoiceField(
        required=True,
        choices=RADIO_CHOICES,
        widget=forms.RadioSelect(
            attrs={
                'required': 'required',
            }
        )
    )

    email = forms.EmailField(
        required=False,
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'maxlength': '254',
            }
        )
    )

    def clean(self):

        username = self.cleaned_data.get('user')
        if username is not None:
            user = UserService.find_by_username(username)
            if user is not None:
                self.add_error('user', _("There cannot be two users with the same username"))
            else:
                dni = self.cleaned_data.get('dni')
                user = StudentService.find_by_dni(dni)
                if user is not None:
                    self.add_error('dni', _("There cannot be two users with the same ID number"))
                else:
                    user = LecturerService.find_by_dni(dni)
                    if user is not None:
                        self.add_error('dni', _("There cannot be two users with the same ID number"))

        return self.cleaned_data


class SubjectEditForm(forms.Form):
    TIPO_ASIGNATURA = (
        ('FB', _('Basic formation')),
        ('OB', _('Compulsory')),
        ('OP', _('Optional')),
        ('TFG', _('Final degree thesis')),

    )

    DURACION = (
        ('A', _('Annual')),
        ('C', _('Quarterly')),
    )

    name = forms.CharField(
        label='name',
        required=True,
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'maxlength': '254',
            }
        )
    )

    course = forms.DecimalField(
        label='course',
        required=True,
        min_value=1,
        max_value=5,
        decimal_places=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'min': '1',
                'max': '5',
            }
        )
    )

    code = forms.DecimalField(
        label='code',
        required=True,
        max_digits=254,
        min_value=0,
        decimal_places=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'min': '0',
                'data-maxlength': '254',
            }
        )
    )

    quarter = forms.DecimalField(
        label='quarter',
        required=True,
        min_value=1,
        max_value=2,
        decimal_places=0,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'min': '1',
                'max': '2',
            }
        )
    )

    credits = forms.DecimalField(
        label='credits',
        required=True,
        min_value=1,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'required': 'required',
                'min': '1',
            }
        )
    )

    web = forms.URLField(
        label='web',
        required=False,
        max_length=254,
        widget=forms.URLInput(
            attrs={
                'class': 'form-control',
                'maxlength': '254',
            }
        )
    )

    duration = forms.ChoiceField(
        required=True,
        choices=DURACION,
        widget=forms.Select(
            attrs={
                'required': 'required',
            }
        )
    )

    type = forms.ChoiceField(
        required=True,
        choices=TIPO_ASIGNATURA,
        widget=forms.Select(
            attrs={
                'required': 'required',
            }
        )
    )

    departament = forms.ModelChoiceField(
        queryset=Departamento.objects.all(),
        required=True,
        widget=forms.Select(
            attrs={
                'required': 'required',
            }
        )
    )

    def clean(self):
        code = self.cleaned_data.get('code')
        if code is not None:
            subject = SubjectService.find_by_code(code)
            if subject is not None:
                self.add_error('code', _("There cannot be two certifications with the same code"))

        return self.cleaned_data


class SubjectLinkEditForm(forms.Form):
    id = forms.IntegerField(widget=forms.HiddenInput)

    certifications = forms.ModelMultipleChoiceField(
        queryset=Titulacion.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(
            attrs={

principal/views/LecturerViews.py
__author__ = 'Carlos'

import json as json_lib

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse

from principal.services import LecturerService


@login_required
def list_lecturers(request, subject_id):
    lecturers = LecturerService.lecturers_of_subject(subject_id)

    return render_to_response('lecturer/list.html', {'lecturers': lecturers},
                              context_instance=RequestContext(request))


def get_lecturers_json(request, subject_id):
    lecturers = LecturerService.lecturers_of_subject(subject_id)
    json = json_lib.dumps(
        [{'id': lecturer.id, 'name': lecturer.first_name + ' ' + lecturer.last_name} for lecturer in lecturers])

    return JsonResponse(json, safe=False)

principal/templates/certification/ajax_search.html
{% load i18n %}

<div class="col-md-6 col-lg-6">
    <div class="page-header">
        <h3><i class="fa fa-graduation-cap"></i> {% trans "Certifications" %}</h3>
    </div>
    {% for certification in certifications %}
        <h6><a href="/admin/certification/details/{{ certification.id }}">{{ certification.nombre }} ({{ certification.codigo }})</a></h6>
    {% empty %}
        {% trans "No certifications found." %}
    {% endfor %}
</div>

principal/templates/certification/details.html
{% extends 'layout/base.html' %}
{% load i18n %}
{% load endless %}
{% block content %}

    <div class="row">
        <h4>{% trans "Certification details" %}</h4>

        <p>{% trans "It displays all the information a certification" %}</p>

        <div class="col-xs-12 col-sm-6">
            <div class="page-header">
                <h3><i class="fa fa-graduation-cap"></i> {% trans "Certification data" %}</h3>
            </div>
            <div>
                <dl class="dl-horizontal custom-dl">
                    <dt>{% trans "Name" %}:</dt>
                    <dd>{{ certification.nombre }}</dd>
                    <dt>{% trans "Code" %}:</dt>
                    <dd>{{ certification.codigo }}</dd>
                </dl>
            </div>
            <a href="/admin/certification/delete/{{ certification.id }}" type="button" class="btn btn-danger"
               onclick="return confirm('{% trans "This action is irreversible. Are you sure you want to delete this certification?" %}')"><i
                    class="fa fa-trash-o"></i> {% trans "Delete" %}</a>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="page-header">
                <h3><i class="fa fa-book"></i> {% trans "Subjects" %}</h3>
            </div>
            <div>
                {% paginate subjects %}
                <ul class="list-unstyled">
                    {% for subject in subjects %}
                        <li>
                            <a href="/subject/details/{{ subject.id }}" data-toggle="tooltip" data-placement="bottom"
                               title="{% trans "Subject details" %}">{{ subject.nombre }}</a>
                            <a href="/admin/subject/unlink/certification/{{ subject.id }}/{{ certification.id }}"
                               data-toggle="tooltip" data-placement="bottom" title="{% trans "Unlink subject" %}"
                               class="unlink_subject"><i class="fa fa-chain-broken"></i></a>
                        </li>
                    {% empty %}
                        <li>{% trans "No subjects found." %}</li>
                    {% endfor %}
                </ul>
                <div class="text-center">
                    <nav class="diggy-pagination">
                        {% show_pages %}
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <script type="application/javascript">
        $('.unlink_subject').on('click', function () {
            return confirm('{% trans "Are you sure you want to unlink subject?" %}');
        });
    </script>

{% endblock %}

principal/templates/certification/edit.html
{% extends 'layout/base.html' %}
{% load i18n %}
{% load extra-tags %}
{% load staticfiles %}

{% block content %}

    <div class="row">
        <div class="col-xs-12">
            <h4>{% trans "Create certification" %}</h4>
            <p>{% trans "It lets you create certifications" %}</p>
            {% display_errors form %}

            <form class="well" role="form" action="/admin/certification/create" method="post" data-toggle="validator">
                {% csrf_token %}

                <div class="form-group col-sm-4">
                    <label for="id_code" class="control-label">{% trans "Code" %}:</label>
                    {{ form.visible_fields.0 }}
                    <div class="help-block with-errors"></div>
                </div>

                <div class="form-group col-sm-8">
                    <label for="id_name" class="control-label">{% trans "Name" %}:</label>
                    {{ form.visible_fields.1 }}
                    <div class="help-block with-errors"></div>
                </div>

                <div class="mb20">
                    <div class="row">
                        <div class="col-xs-12 col-sm-2">
                            <button type="submit" class="btn btn-primary btn-block">{% trans "Save changes" %}</button>
                        </div>
                    </div>
                </div>

            </form>

        </div>

    </div>

{% endblock %}

principal/templates/certification/list.html
{% extends 'layout/base.html' %}
{% load i18n %}
{% load endless %}
{% load staticfiles %}

{% block content %}

    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class=" col-md-8 col-lg-8">
                    <h4>{% trans "Certification list" %}</h4>
                    <p>{% trans "It shows a list of all certifications which are registered in the system" %}</p>
                </div>
                <div class="col-md-4  col-lg-4 text-right">
                    <div style="margin-top: 15px">
                        <div class="input-group col-md-12">
                            {% csrf_token %}
                            <input type="text" id="search" name="search" class="form-control input-lg" placeholder={% trans "Search" %} />
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-lg" type="button"><i class="glyphicon glyphicon-search"></i></button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div id="search-results" class="col-lg-12">
                <div class="col-md-7 col-lg-7">
                    <div class="page-header">
                        <h3><i class="fa fa-graduation-cap"></i> {% trans "Certifications" %}</h3>
                    </div>
                    {% paginate certifications %}
                    {% for certification in certifications %}
                        <h6><a href="/admin/certification/details/{{ certification.id }}">{{ certification.nombre }} ({{ certification.codigo }})</a></h6>
                    {% empty %}
                        {% trans "No certifications found." %}
                    {% endfor %}
                    <div class="text-center">
                        <nav class="diggy-pagination">
                            {% show_pages %}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="application/javascript">
        $(function(){
            $('#search').keyup(function(){
                $.ajax({
                    type: "POST",
                    url: "/admin/certification/search/",
                    data: {
                        'search_text' : $('#search').val(),
                        'csrfmiddlewaretoken' : $("input[name = csrfmiddlewaretoken]").val()
                    },
                    success: searchSuccess,
                    dataType: 'html'
                });
            });

        });

        function searchSuccess(data, textStatus, jqXHR){
            $('#search-results').html(data);
        }
    </script>

{% endblock %}